[package]
name = "ppk"
version = "0.1.1"
edition = "2021"
authors = ["lrwx00t"]
description = "find the port, and kill its process!"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netstat2 = "0.9.1"
psutil = "3.2.2"
